### PR TITLE
Raise an error if a model doesn't have an attribute

### PR DESCRIPTION
**Pull request by Moliholy**
This PR addresses the issue https://github.com/django-tastypie/django-tastypie/issues/1537

Description of the problem
====================

As explained in the issue, in version 0.14.0 this bug was introduced. I just restored the previous status of the code.

### CODE REVIEW

**Comment by Moliholy** [comment]
UPDATE:
=======

It turned out to happen when the model doesn't have an attribute, so what I did instead was to raise an error specifying the reason.

**Comment by georgedorn** [comment]
@Moliholy From my own investigation, this bug can happen on non-model resources, too.  For example, if you provide an `attribute` lamda function that returns None, which is a valid value when `null=True`.

**Comment by Moliholy** [comment]
Yes, this happened in my case because I had a very big model with lots of relationships between different entities and one of them turned out to have a bad attribute name by mistake. Before 0.14.0 I didn't notice because it wasn't an important attribute and nothing broke, but when making the migration to Django 1.11 and python3 I realized there was no way to make one of my own test pass. It took me a while to discover we were using a wrong attribute name, so my first approach was to simply return an empty array as before, but in my opinion it'd be better to raise an exception, mainly because that'd guide the developer in the right way and at the same time avoid situations where nothing breaks but nothing works.

I hope the explanation shows some light over this issue!

**Comment by georgedorn** [comment]
Yeah, your situation should raise an exception, but the lambda situation shouldn't.  It sounds like we're missing a sanity check during `ToManyField.__init__()`.

**Comment by georgedorn** [comment]
So there are no sanity checks during `ToManyField.__init__()`, but further testing reveals that an `ApiFieldError` is already raised if you specify a bad attribute by string.  Weirdly, it's valid to add an attribute with an invalid name that is always null; I don't know why you'd want to, but it also means you can POST to that attribute a list of random nonsense and it won't cause an error during hydration, so maybe there's a weird edge case people might use that for?

In any case, it looks like all of the major cases are covered by the existing code and the fix in #1544, so I can finally merge that one and cut a release.

**Pull request closed without merging**
