### PR TITLE
Django 1.8

### PR DESCRIPTION
**Pull request by georgedorn**
This is a rollup of the 1.8 atomic/transaction fixes from #1263 and a bunch of fixes for failing tests.  

The whole thing needs a review, preferably by somebody with a stronger understanding of the related_resources tests and the save_related() method on Resource.

I got a green board to happen (https://travis-ci.org/django-tastypie/django-tastypie/builds/51335501), but I got there with a bit of fumbling through save_related() and I don't fully understand why I needed to do what I did.

### CODE REVIEW

**Comment by georgedorn** [comment]
We've got some kind of issue on travis, where the 3.3-1.8 tests keep dying with a 'port already in use' error.  Have we uncovered a bug in Django itself?

**Comment by coagulant** [comment]
>We've got some kind of issue on travis, where the 3.3-1.8 tests keep dying with a 'port already in use' error.
Can we get rid of TestServerTestCase in favor of LiveServerTestCase? I guess they serve the same purpose, but latter is maintained by Django core )

**Comment by coagulant** [comment]
I've tested against latest Django==1.8b1, and it looks like problem is solved.

**Comment by georgedorn** [comment]
I'm also in favor of ditching TestServerTestCase, but I'm not sure if LiveServerTestCase is a drop-in replacement.

**Comment by georgedorn** [comment]
A code review would be appreciated; there are a lot of changes, but now Travis is happy and 1.8 is days away from official release...

If nobody has comments or concerns, I'm going to merge this when 1.8 officially drops.  If there are more beta point releases I'll update the CI spec accordingly, but it'd be nice to time a PyPI release to coincide with the official 1.8 release.

**Comment by coagulant** [comment]
I'm also concerned about related_resources changes in 64d55b34, I don't exactly understand what's going on there too :)
Other commits seem to be straightforward changes.

**Comment by georgedorn** [comment]
Another option, if nobody really groks the save_related() code, would be to audit the related tests for use case coverage.  If we're confident that those tests cover all of the known use cases for related models, we can be confident that my PR at least doesn't break anything even if it may not be the most efficient approach.

**Comment by georgedorn** [comment]
So are we doing this?  I could just merge and wait for bug reports from the few users of the master branch...

**Comment by jonathanmorgan** [comment]
So, are you doing this?  Should I just remove tastypie for now to get to 1.8?  Not a problem at the moment, just prepping for a stretch of work where I want stable django, trying to get to 1.8 before starting.

Thanks,

Jonathan Morgan

**Comment by aisayko** [comment]
+1 

waiting for support django 1.8

**Comment by Itxaka** [comment]
:+1: I'll test master with my django 1.8 project if needed

**Comment by georgedorn** [comment]
Django 1.8 support is now in master.  Please file any bugs you find, but also search for existing issues to avoid duplicates.

**Comment by mlissner** [comment]
It's now five months since support for Django 1.8 is in master (according to this issue), and Django 1.8 was released around the same time. 

Is there anything that I can do to help get support for 1.8 out the door so folks don't have to install the master branch? We have been doing a HUGE upgrade from Django 1.5 to 1.8, and this is the only blocking dependency we have.

**Comment by jonathanmorgan** [comment]
I have switched to django rest framework.  Works fine with 1.8.

**Comment by mlissner** [comment]
Unfortunately, many organizations rely on old versions of our API. Making a switch is very impractical.

**Comment by jonathanmorgan** [comment]
I understand.  I got lucky in that I was just starting to build out an API when this issue arose.  Good luck!

**Comment by aisayko** [comment]
Sorrowfully, hello django-rest-framework :(

**Comment by SeanHayes** [comment]
I believe this PR has been released here: https://pypi.python.org/pypi/django-tastypie/0.12.2

https://github.com/django-tastypie/django-tastypie/releases/tag/v0.12.2

**Comment by mlissner** [comment]
Funny, I just filed bug #1345 for getting 0.12.2 properly documented!

I thought I was having problems with that installed, but I'll double check now. If that's done, can we close this issue?

**Comment by SeanHayes** [comment]
I understand everyone's frustrations. I just want everyone to know that the other contributors and I have put in a lot of effort over the past few weeks to get this project active again and resolve old issues and PRs. We now check code coverage, check code quality, and have made performance improvements, and we're working on more changes to make Tastypie an up to date and competitive framework to use.

**Comment by SeanHayes** [comment]
@mlissner Let us know how it goes. If you could, let me know how things work with the latest master too, we may want to prepare another release.

**Comment by georgedorn** [comment]
Bug #1345 is correct; I could have sworn I wrote release notes for 0.12.2, but they never made it into master.  If nobody else gets to them before I do, I'll track down wherever I left them and get them into a PR.

The main summary is that django 1.8 is supported; there were a couple other small changes that I'm not sure about at the moment.

**Comment by mlissner** [comment]
Wow, this issue took a major turn for the better! Thanks for all the responses. I'll be vocal as I run into things. Looking forward to what's in the pipe!

**Comment by OneReceipt** [comment]
just FYI, I have been using v0.2.12 on production for about a month with a decent size of traffic with no issues. +1!

**Comment by hassek** [comment]
just FYI, I have been using tastypie v0.12.2 since the release finally got out and is running very well. I have to admit is a different case since we run it with mongodb but it's very stable and reliable.

**Pull request merged**
