### PR TITLE
Bug/race condition test

### PR DESCRIPTION
**Pull request by georgedorn**
Re-fixed the tests to ensure they fail without the change to patch.

### CODE REVIEW

**Comment by georgedorn** [comment]
@EndermanAPM As you can see from the checks here, once the flake8/app_label issues are fixed, the tests don't fail successfully...

**Comment by EndermanAPM** [comment]
@georgedorn Created #1681 that adds the tests to the innit, it should make it fail now. I'm pointing the PR to this branch.

**Comment by EndermanAPM** [comment]
p.s. @georgedorn If you're part of the maintainers you could've just updated my PR, that would have avoided having to create 5 different PRs. :smile:

**Comment by EndermanAPM** [comment]
@georgedorn It seems that now it properly fails. What are the following steps? Will you merge this onto #1671 ?

**Comment by georgedorn** [comment]
> @georgedorn It seems that now it properly fails. What are the following steps? Will you merge this onto #1671 ?

Yup, doing that now.  Github wasn't realizing I needed to rebase 1671 so I had to do that manually, but now this branch is part of that one.  If all goes well, I'll then merge it into master later today and get started cutting a release.

**Pull request merged**
