### PR TITLE
Tastypie sends back data in PUT

### PR DESCRIPTION
**Pull request by graingert**
Tastypie sends back data in PUT

### CODE REVIEW

**Comment by SeanHayes** [comment]
https://travis-ci.org/django-tastypie/django-tastypie/builds/23915017

**Comment by SeanHayes** [comment]
So, the tests seem to work fine except for the Sphinx docs.

**Comment by SeanHayes** [comment]
@georgedorn I fine with this as long as you are.

**Comment by graingert** [comment]
So I presume this got transparently fixed? Can we add this unittest anyway?

**Comment by SeanHayes** [comment]
@georgedorn Sorry, I meant to tag you in a different PR.

**Comment by SeanHayes** [comment]
Merged, thanks!

**Pull request merged**
