### PR TITLE
Removed obsolete Django 1.3/1.4 compatibility code (current minimum …

### PR DESCRIPTION
**Pull request by SeanHayes**
…supported version is 1.5).

### CODE REVIEW

**Comment by georgedorn** [comment]
We technically could stop running tests against 1.6 as well - that version
is essentially EOL.

**Comment by SeanHayes** [comment]
I'd be in favor of that, though that would involve even more changes, such as removing South migrations.

**Comment by SeanHayes** [comment]
@georgedorn If you're OK with this PR, we can merge it in, then I'll get started on a new PR removing Django 1.5 and 1.6 support.

**Comment by georgedorn** [comment]
Oh, yeah, :+1:

**Pull request merged**
