### PR TITLE
Allow creation of related resources that have an 'items' related_name on post

### PR DESCRIPTION
**Pull request by mthornhill**
Use a stricter check for a dictionary when building related resources

### CODE REVIEW

**Comment by SeanHayes** [comment]
Looks good, we just need the merge conflicts fixed.

**Comment by mthornhill** [comment]
Hi Sean,
I've merged master into the strict_dict_check, does everything look ok?
Thanks
Michael

**Comment by SeanHayes** [comment]
Thanks. I rebased your changes onto master and opened a new PR. It should be merged shortly.

**Comment by mthornhill** [comment]
Brilliant, thanks.

On Wed, Sep 9, 2015 at 4:43 PM, Seán Hayes <notifications@github.com> wrote:

> Closed #1000
> <https://github.com/django-tastypie/django-tastypie/pull/1000>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/django-tastypie/django-tastypie/pull/1000#event-404973341>
> .
>



-- 
p: +353 87 6124111
e: michael@maithu.com

**Comment by mthornhill** [comment]
ps, Any chance I can be added to Authors file?

**Comment by SeanHayes** [comment]
No problem, just let me know what you want your author line to be, or open a PR.

**Comment by mthornhill** [comment]
Hi Sean,
Michael Thornhill (mthornhill)
would be great, thanks
Michael

On Wed, Sep 9, 2015 at 5:23 PM, Seán Hayes <notifications@github.com> wrote:

> No problem, just let me know what you want your author line to be, or open
> a PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/django-tastypie/django-tastypie/pull/1000#issuecomment-138962590>
> .
>



-- 
p: +353 87 6124111
e: michael@maithu.com

**Comment by SeanHayes** [comment]
Done

**Comment by mthornhill** [comment]
Brilliant, thanks


On Wed, Sep 9, 2015 at 10:32 PM, Seán Hayes <notifications@github.com>
wrote:

> Done
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/django-tastypie/django-tastypie/pull/1000#issuecomment-139052035>
> .
>



-- 
p: +353 87 6124111
e: michael@maithu.com

**Pull request closed without merging**
