### PR TITLE
Reorder blank, null checks in full_hydrate - #1489

### PR DESCRIPTION
**Pull request by pawelswiecki**
This is a resubmitted fix proposed by @aaronelliotross. See issue page https://github.com/django-tastypie/django-tastypie/issues/1489 for discussion on resubmitting pull request. 

Original commit:
https://github.com/aaronelliotross/django-tastypie/commit/bd46c5a1a348e84e9c01f90f71bf49afd3c5c5e4

Original pull request:
https://github.com/django-tastypie/django-tastypie/pull/1494.

### CODE REVIEW

**Comment by pawelswiecki** [comment]
Travis fails on flake8 step:

```
./tastypie/authentication.py:79:9: E722 do not use bare except'
./tastypie/resources.py:2266:13: E722 do not use bare except'
./tests/core/tests/resources.py:852:9: E722 do not use bare except'
./tests/core/tests/resources.py:4550:9: E722 do not use bare except'
```

Those failures are unrelated to the PR and I believe they should not block merging it.

**Comment by pawelswiecki** [comment]
Created a separate issue for flake8 errors: https://github.com/django-tastypie/django-tastypie/issues/1540.

**Comment by pawelswiecki** [comment]
@SeanHayes @georgedorn Hello guys! Could you take a look at this PR? It would really help my project if you could push this forward. Also, see this PR that deals with flake8 errors: https://github.com/django-tastypie/django-tastypie/issues/1540. 

Thanks in advance!

**Comment by georgedorn** [comment]
Reopening to trigger new build.

**Comment by georgedorn** [comment]
Thanks for the test; we need more tests for these edge cases.

**Comment by pawelswiecki** [comment]
Thank you!

**Pull request merged**
