### PR TITLE
Fix race condition between POST / PATCH resources by using update_fields...

### PR DESCRIPTION
**Pull request by quietlyconfident**
Fixes issue #1150  by:
- Creating an update_fields list on the bundle during a patch
- Creating an m2m_update_fields list on the bundle during a patch
- During save, passing arguments to save to only update the changed data: save(update_fields=bundle.update_fields) 
- During save_m2m , don't save fields unless they appear in m2m_fields

### CODE REVIEW

**Comment by SeanHayes** [comment]
https://travis-ci.org/django-tastypie/django-tastypie/builds/41000585

**Comment by EndermanAPM** [comment]
I've _stole_ this idea to create a custom resource that overrides the methods and it works, would be great to add this to the tastypie codebase.

After reading the source for the whole afternoon to find a solution, I don't understand why you shoehorn the patch method into the put instead of doing the reverse, and only updating the provided fields. Wouldn't be easier to convert the PUT in a "full PATCH"?

**Comment by Poshi** [comment]
I've been hitting the issue related to this PR during the last days. And it looks like there's already a solution offered! Could someone take a look at this and merge the PR for the next release?
That would solve a quite relevant bug, as the code in its current state breaks the compliance with their corresponding [RFC](https://datatracker.ietf.org/doc/html/rfc5789#section-2):

> The server MUST apply the entire set of changes atomically and never provide (e.g., in response to a GET during this operation) a partially modified representation.

**Comment by georgedorn** [comment]
This PR is ten years old and cannot possibly be merged.  It couldn't be merged when it was created as it didn't match the style (semicolons, no spaces between args, other flake8 issues), failed existing tests and didn't provide test coverage for the new behavior.  The original author didn't come back to rectify any of that in the last decade.

The best I can do at the moment is cherry-pick this PR into a new branch off `master` and at least address the style issues.  I have done so in #1671.  If somebody would like to take a crack at testing it and proving it works (ideally in the form of a test case that fails on `master` but passes on `quietlyconfident-master`) I am happy to review and merge it.

As another option, if @EndermanAPM  would like to contribute his rework as a PR, I'm happy to look at it, and @Poshi could try it out in his scenario to see if it solves his issue as well.

**Pull request closed without merging**
